#!/usr/bin/env zsh

successfully() {
  $* || (echo "failed" 1>&2 && exit 1)
}

echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "Copying public key to clipboard. Paste it into your Github account ..."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
  successfully open https://github.com/account/ssh

echo "Fixing permissions ..."
  successfully sudo mkdir -p /usr/local
  successfully sudo chown -R `whoami` /usr/local

echo "Installing Homebrew, a good OS X package manager ..."
  successfully ruby <(curl -fsS https://raw.github.com/mxcl/homebrew/go)
  successfully brew update

echo "Installing zsh, a good shell ..."
  successfully brew install zsh

echo "Installing direnv, a good way to manage your path ..."
  successfully brew install direnv

echo "Creat Launch Agent directory for auto start of services"
mkdir -p ~/Library/LaunchAgents

echo "Putting Homebrew location earlier in PATH and adding ruby gem bin ..."
  successfully echo "
# recommended by brew doctor
export PATH='/usr/local/bin:$(cd $(which gem)/..;pwd):$PATH'" >> ~/.zshenv
  successfully source ~/.zshenv

echo "Installing system libraries recommended for Ruby"
  successfully brew install gdbm libffi libksba libyaml

echo "Installing Postgres, a good open source relational database ..."
  successfully brew install postgres --no-python
  successfully initdb /usr/local/var/postgres -E utf8
  successfully ln -sfv /usr/local/opt/postgresql/*.plist ~/Library/LaunchAgents

echo "Installing Memcached, a good open source memory store (for caching)"
  successfully brew install memcached
  successfully ln -sfv /usr/local/opt/memcached/*.plist ~/Library/LaunchAgents

echo "Installing Redis, a good key-value database ..."
  successfully brew install redis
  successfully ln -sfv /usr/local/opt/redis/*.plist ~/Library/LaunchAgents

echo "Installing The Silver Searcher (better than ack or grep) for searching the contents of files ..."
  successfully brew install the_silver_searcher

echo "Installing ctags, for indexing files for vim tab completion of methods, classes, variables ..."
  successfully brew install ctags

echo "Installing tmux, for saving project state and switching between projects ..."
  successfully brew install tmux

echo "Installing reattach-to-user-namespace, for copy-paste and RubyMotion compatibility with tmux ..."
  successfully brew install reattach-to-user-namespace

echo "Installing ImageMagick, for cropping and re-sizing images ..."
  successfully brew install imagemagick

echo "Installing QT, used by Capybara Webkit for headless Javascript integration testing ..."
  successfully brew install qt

echo "Installing watch, used to execute a program periodically and show the output ..."
  successfully brew install watch

echo "Installing hombrew/versions for installing old versions of packages"
  successfully brew tap homebrew/versions

echo "Installing Ruby 2.0.0, which will be the default ..."
  successfully brew install ruby

echo "Update to latest Rubygems version ..."
  successfully gem update --system

echo "Installing critical Ruby gems for Rails development ..."
  successfully gem install bundler foreman pg rails --no-ri --no-rdoc -f

echo "Installing GitHub CLI client ..."
  successfully gem install hub --no-ri --no-rdoc

echo "Installing Heroku CLI client ..."
  successfully brew install heroku-toolbelt

echo "Installing the heroku-config plugin for pulling config variables locally to be used as ENV variables ..."
  successfully heroku plugins:install git://github.com/ddollar/heroku-config.git

echo "Your shell will now restart in order for changes to apply."
  exec $SHELL -l
